"""
API Router for the Todo List Application

This module defines the API endpoints that map to the existing CLI functionality.
Each endpoint corresponds to a command that was previously available in the CLI parser.
"""

from fastapi import APIRouter

router = APIRouter()

# Project Management Endpoints
# Corresponds to CLI command: create-project <name> <description>
@router.post("/projects")
def create_project():
    """
    Create a new project with name and description
    CLI equivalent: create-project <name> <description>
    """
    pass


# Corresponds to CLI command: list-projects
@router.get("/projects")
def list_projects():
    """
    List all projects
    CLI equivalent: list-projects
    """
    pass


# Corresponds to CLI command: edit-project <id> <new_name> <new_desc>
@router.put("/projects/{project_id}")
def edit_project(project_id: int):
    """
    Edit an existing project by ID
    CLI equivalent: edit-project <id> <new_name> <new_desc>
    """
    pass


# Corresponds to CLI command: delete-project <id>
@router.delete("/projects/{project_id}")
def delete_project(project_id: int):
    """
    Delete a project by ID
    CLI equivalent: delete-project <id>
    """
    pass


# Task Management Endpoints
# Corresponds to CLI command: create-task <project_id> <title> <description> [deadline YYYY-MM-DD] [status]
@router.post("/tasks")
def create_task():
    """
    Create a new task in a project
    CLI equivalent: create-task <project_id> <title> <description> [deadline YYYY-MM-DD] [status]
    """
    pass


# Corresponds to CLI command: list-tasks <project_id>
@router.get("/projects/{project_id}/tasks")
def list_tasks_for_project(project_id: int):
    """
    List all tasks for a specific project
    CLI equivalent: list-tasks <project_id>
    """
    pass


# Corresponds to CLI command: edit-task <task_id> <new_title> <new_desc> <new_deadline> <new_status>
@router.put("/tasks/{task_id}")
def edit_task(task_id: int):
    """
    Edit an existing task by ID
    CLI equivalent: edit-task <task_id> <new_title> <new_desc> <new_deadline> <new_status>
    """
    pass


# Corresponds to CLI command: delete-task <task_id>
@router.delete("/tasks/{task_id}")
def delete_task(task_id: int):
    """
    Delete a task by ID
    CLI equivalent: delete-task <task_id>
    """
    pass


# Utility Endpoints
# API documentation will be available at /docs (auto-generated by FastAPI)